language: python
python:
- '3.6'
install:
- pip install .
- pip install -r test_requirements.txt
script: pytest
deploy:
  provider: pypi
  user: dchiquit
  password:
    secure: tHojHq8pCRCXaXoRHEUiERMOLkVUE02j1R9627e1Q+KxoxRHpMGqlK72fWbiMdiYnZyKHt6Go56FJzbRGhlotTVyNoUUQt2MI1ottuiFCzpIR6Vp1HAU4xqPu84K6nTCcbH7jWdLZBQUt68ATdeXJHdqtZahmLIKBaStHTFrCfeKRtN1sUXnRc3CjmQRO5XMZEBatP8+/uk3+w4f4Jl4U1y+LrCdvrZbStYkdN0mIEjea7I4W547TgHPM9zMm683DY1DANXXNA5kzd40LzZ0m6h/ml3L4xbxGpX+cnMjnuWmsERp7ANxHPUQHKML1dHGyZeB7zkHJlxEAsOs2MBU7t8A3fRk4CFNwaQWCMmneUFvI5x592g3pHF4UsK+y8SL0prX46pXQQG44k9osBlS3faHjtK6HOh33FzwUYoACTzWxw/gsfUCBPdSyjv0/6M+L4ARWXg3Eqfgm67ZO8zRfROhxgqHxjVjEeC0iDEazkLRyL/y8Fc5RVwB46vLguvlKbWlg+6jhzexFTzt0ixADwV1rwdSTketYoScf685MZcL5va74j3D8JDGP8z1PYhyDEZ82UsG6AWpmbsRjcodx0qB7hSLyrKx+5aD10DpdH5f6tMGtymqCfPUwEwvyt2WwpX5D/YgBYJiSHMOms6xWb2Pejcj8QL6k7I/Saer0ng=
  on:
    branch: master
    tags: true
  skip_cleanup: true
